title: "GlitchSoc Specifications"
description: "Specifications for OStatus servers"
lang: "en"
timezone: "America/Toronto"
collections:
  Draft:
    output: true
    permalink: "/WD/:path/"
  Candidate:
    output: true
    permalink: "/RC/:path/"
  Final:
    output: true
    permalink: "/FR/:path/"
  Errata:
    output: true
    permalink: "/ER/:path/"
defaults:
  -
    scope:
      path: ""
      type: "Draft"
    values:
      layout: "spec"
  -
    scope:
      path: ""
      type: "Candidate"
    values:
      layout: "spec"
  -
    scope:
      path: ""
      type: "Final"
    values:
      layout: "spec"
gems:
  - "jekyll-github-metadata"
exclude:
  - 'buildspec.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
